### ISSUE TITLE
user list item 컴포넌트 구현

### ISSUE THREAD

**Issue by aoooec** [Mogazoa-team20/mogazoa#12]
## 요약
- 리뷰어 랭킹, 리뷰 목록 내부에서 사용될 유저 아이템 컴포넌트를 구현합니다. 

## ToDo
- [x] chip 컴포넌트를 제외한 리뷰/랭킹 내부 유저 아이템 컴포넌트 구현 
- [x] rating에 따른 아이콘 출력
- [x] 반응형 디자인 적용 
- [x] 팔로워/리뷰 수 포맷팅 함수 생성
- [ ] 등수 표시 코드 chip 컴포넌트로 변경
