### ISSUE TITLE
마이 페이지

### ISSUE THREAD

**Issue by yeeZinu** [Mogazoa-team20/mogazoa#35]
## 요약
마이페이지를 구현합니다

## ToDo
- [x] 들어오는 데이터에 따라 마이페이지와 상대 페이지 분기
- [x] 프로필 컴포넌트 구현하기 (유저이미지, 팔로우, 활동 등)
- [x] 활동 내역 컴포넌트 구현하기
- [x] 활동 내역 상품 리스트 컴포넌트 구현하기. 
- [x] 팔로워 팔로우 모달 구현하기
- [x] 마이페이지 파일 경로 수정하기
- [x] api 달아주기
- [ ] #86
