### ISSUE TITLE
profile image 컴포넌트 구현

### ISSUE THREAD

**Issue by aoooec** [Mogazoa-team20/mogazoa#9]
## 요약
- 공통 프로필 이미지 컴포넌트를 구현합니다.

## ToDo
- [x] 유저 프로필 이미지가 존재하지 않을 경우 노출될 기본 이미지 에셋 추가
- [x] 랭킹, 리뷰/프로필 화면/팔로잉, 팔로워 리스트 3가지 경우를 고려해 컴포넌트 생성
- [x] 반응형 사이즈 적용
